version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: api_dev
    volumes:
      - ./server:/app/server
    ports:
      - "3000:3000"
    env_file:
      - .env
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./index.ts
          action: rebuild
        - path: ./server
          target: /app/server
          action: sync

  app:
    container_name: expanse-app
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend_dev
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    depends_on:
      - api
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./vite.config.ts
          action: rebuild
        - path: ./frontend
          target: /app/frontend
          action: sync
